# ==============================================================================
# Merged Lakeflow Source: dualentry
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence
import json
import sys

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
from urllib.parse import urljoin
import base64
import logging
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/dualentry/dualentry.py
    ########################################################

    logger = logging.getLogger(__name__)


    DEFAULT_BASE_URL = "https://api.dualentry.com"

    # HTTP retry knobs — used by the lightweight retry helper.
    INITIAL_BACKOFF = 1.0
    MAX_RETRIES = 5
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    DEFAULT_TIMEOUT = 30

    # ``limit`` query param: DualEntry default and server max are both 100.
    DEFAULT_PAGE_SIZE = 100
    MAX_PAGE_SIZE = 100

    # Read-time lookback for CDC ranges. Records updated while a bounded range is
    # being paginated fall out of the range's filter (their new ``updated_at``
    # exceeds the pinned upper bound) and can shift pagination; re-reading a small
    # overlap on the next trigger re-captures them. Upserts make the overlap
    # harmless.
    DEFAULT_LOOKBACK_SECONDS = 300


    # Table → endpoint path (all list endpoints wrap records in a top-level
    # ``items`` array).
    TABLE_ENDPOINTS: dict[str, str] = {
        "accounts": "public/v2/accounts/",
        "journal_entries": "public/v2/journal-entries/",
        "invoices": "public/v2/invoices/",
        "bills": "public/v2/bills/",
        "customers": "public/v2/customers/",
        "vendors": "public/v2/vendors/",
        "items": "public/v2/items/",
    }


    # Ingestion-type metadata — primary keys and cursor fields per table. Kept as a
    # module-level constant so it stays in sync with TABLE_SCHEMAS. Primary keys
    # are per the OpenAPI list-item schemas and differ across streams.
    TABLE_METADATA: dict[str, dict] = {
        # Snapshot tables (no updated_at cursor / filter on the wire).
        "accounts": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        "customers": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        "vendors": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        "items": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        # CDC tables: server-side updated_after/updated_before filter plus a
        # required ``updated_at`` on every record. Primary keys differ per stream.
        "journal_entries": {
            "primary_keys": ["internal_id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "invoices": {
            "primary_keys": ["internal_id"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
        "bills": {
            "primary_keys": ["number"],
            "cursor_field": "updated_at",
            "ingestion_type": "cdc",
        },
    }


    def _build_schemas() -> dict[str, StructType]:
        """Return the static schema dictionary.

        Field names are kept exactly as the API returns them (snake_case) so raw
        records map 1:1 onto the DualEntry OpenAPI list-item schemas. Monetary
        quantities (``amount``, ``amount_due``, ``paid_total``, ``exchange_rate``)
        are strings on the wire and are typed ``StringType`` to preserve precision.
        ``*_at`` fields are ``TimestampType``; bare date fields are ``DateType``.
        Genuinely polymorphic / untyped payloads are ``VariantType``. See
        ``dualentry_api_doc.md`` for the extraction notes.
        """

        audit_actor = StructType(
            [
                StructField("actor_type", StringType()),
                StructField("email", StringType()),
                StructField("first_name", StringType()),
                StructField("last_name", StringType()),
                StructField("timestamp", TimestampType()),
            ]
        )
        # AddressSchemaOut (invoices billing/shipping addresses).
        address_out = StructType(
            [
                StructField("name", StringType()),
                StructField("street", StringType()),
                StructField("second_line", StringType()),
                StructField("city", StringType()),
                StructField("state", StringType()),
                StructField("postal_code", StringType()),
                StructField("country", StringType()),
            ]
        )
        # AddressSchemaIn (customer full/shipping addresses).
        address_in = StructType(
            [
                StructField("street", StringType()),
                StructField("city", StringType()),
                StructField("state", StringType()),
                StructField("postal_code", StringType()),
                StructField("country", StringType()),
                StructField("second_line", StringType()),
                StructField("name", StringType()),
            ]
        )
        # PublicVendorListAddressSchemaOut.
        vendor_address = StructType(
            [
                StructField("street", StringType()),
                StructField("city", StringType()),
                StructField("state", StringType()),
                StructField("postal_code", StringType()),
                StructField("country", StringType()),
                StructField("second_line", StringType()),
            ]
        )
        attachment = StructType(
            [
                StructField("id", LongType()),
                StructField("file_name", StringType()),
                StructField("file_size", LongType()),
                StructField("download_url", StringType()),
            ]
        )
        payment = StructType(
            [
                StructField("type", StringType()),
                StructField("id", LongType()),
                StructField("body", StringType()),
                StructField("link", StringType()),
            ]
        )
        rejected_by = StructType(
            [
                StructField("id", LongType()),
                StructField("first_name", StringType()),
                StructField("last_name", StringType()),
                StructField("email", StringType()),
                StructField("full_name", StringType()),
                StructField("rejection_reason", StringType()),
            ]
        )
        # next_approvers[] — ApproverDictSchema.
        approver = StructType(
            [
                StructField("id", LongType()),
                StructField("first_name", StringType()),
                StructField("last_name", StringType()),
                StructField("email", StringType()),
                StructField("full_name", StringType()),
                StructField("avatar_url", StringType()),
            ]
        )
        # custom_fields[] — CustomFieldValuePairOutputSchema = {field, value}.
        # ``field`` is the definition (CustomFieldSchemaOut); ``value`` is the
        # instance value (CustomFieldValueSchemaOut). Their untyped leaves
        # (``value.value``, ``company_ids``, ``options``, ``default_value``) are
        # ``VariantType`` — the DualEntry API leaves them user-defined.
        custom_field_definition = StructType(
            [
                StructField("id", LongType()),
                StructField("company_id", LongType()),
                StructField("company_ids", VariantType()),
                StructField("name", StringType()),
                StructField("description", StringType()),
                StructField("helper_text", StringType()),
                StructField("field_type", StringType()),
                StructField(
                    "applies_to",
                    ArrayType(
                        StructType(
                            [
                                StructField("type", StringType()),
                                StructField("is_active", BooleanType()),
                                StructField("is_required", BooleanType()),
                            ]
                        )
                    ),
                ),
                StructField("default_value", VariantType()),
                StructField("options", VariantType()),
                StructField("is_active", BooleanType()),
            ]
        )
        custom_field_value = StructType(
            [
                StructField("id", LongType()),
                StructField("custom_field_id", LongType()),
                StructField("custom_field_name", StringType()),
                StructField("custom_field_type", StringType()),
                StructField("custom_field_value_id", LongType()),
                StructField("value", VariantType()),
                StructField("created_at", StringType()),
                StructField("updated_at", StringType()),
            ]
        )
        custom_fields = ArrayType(
            StructType(
                [
                    StructField("field", custom_field_definition),
                    StructField("value", custom_field_value),
                ]
            )
        )
        # TaxRegistrationNumbersSnapshot = {company: [entry], counterparty: [entry]}.
        tax_reg_entry = StructType(
            [
                StructField("type", StringType()),
                StructField("number", StringType()),
                StructField("region", StringType()),
            ]
        )
        tax_registration_numbers = StructType(
            [
                StructField("company", ArrayType(tax_reg_entry)),
                StructField("counterparty", ArrayType(tax_reg_entry)),
            ]
        )
        # RecordTaxContextOut = {regime, data}. ``data`` is a documented union of
        # per-regime tax-data objects (sales_tax / vat / gst / none) — modelled as
        # VariantType so any member is preserved raw.
        bill_tax = StructType(
            [
                StructField("regime", StringType()),
                StructField("data", VariantType()),
            ]
        )

        return {
            "accounts": StructType(
                [
                    StructField("id", LongType()),
                    StructField("name", StringType()),
                    StructField("number", LongType()),
                    StructField("description", StringType()),
                    StructField("is_active", BooleanType()),
                    StructField("is_system", BooleanType()),
                    StructField("company_id", LongType()),
                    StructField("parent_account_id", LongType()),
                    StructField("account_type", StringType()),
                    StructField("currency_iso_4217_code", StringType()),
                    StructField("category_1099", StringType()),
                    StructField("system_ref", StringType()),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                ]
            ),
            "journal_entries": StructType(
                [
                    StructField("internal_id", LongType()),
                    StructField("number", LongType()),
                    StructField("transaction_id", LongType()),
                    StructField("company_id", LongType()),
                    StructField("company_name", StringType()),
                    StructField("company_currency", StringType()),
                    StructField("memo", StringType()),
                    StructField("date", DateType()),
                    StructField("transaction_date", DateType()),
                    StructField("reversal_date", DateType()),
                    StructField("currency_iso_4217_code", StringType()),
                    StructField("amount", StringType()),
                    StructField("exchange_rate", StringType()),
                    StructField("record_status", StringType()),
                    StructField("approval_status", StringType()),
                    StructField("bank_match_status", StringType()),
                    StructField("reconciliation_status", StringType()),
                    StructField("custom_fields", custom_fields),
                    StructField("attachments", ArrayType(attachment)),
                    StructField("next_approvers", ArrayType(approver)),
                    StructField("rejected_by", rejected_by),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                    StructField("created_at", TimestampType()),
                    StructField("updated_at", TimestampType()),
                ]
            ),
            "invoices": StructType(
                [
                    StructField("internal_id", LongType()),
                    StructField("number", LongType()),
                    StructField("code", StringType()),
                    StructField("company_id", LongType()),
                    StructField("company_name", StringType()),
                    StructField("company_currency", StringType()),
                    StructField("customer_id", LongType()),
                    StructField("customer_name", StringType()),
                    StructField("currency_iso_4217_code", StringType()),
                    StructField("exchange_rate", StringType()),
                    StructField("amount", StringType()),
                    StructField("amount_due", StringType()),
                    StructField("paid_total", StringType()),
                    StructField("amount_due_updated_at", TimestampType()),
                    StructField("memo", StringType()),
                    StructField("date", DateType()),
                    StructField("transaction_date", DateType()),
                    StructField("due_date", DateType()),
                    StructField("record_status", StringType()),
                    StructField("approval_status", StringType()),
                    StructField("recurring_record_number", LongType()),
                    StructField("reference_number", StringType()),
                    StructField("term_id", LongType()),
                    StructField("term_name", StringType()),
                    StructField("transaction_ids", ArrayType(LongType())),
                    StructField("bill_to_address", StringType()),
                    StructField("ship_to_address", StringType()),
                    StructField("billing_address", address_out),
                    StructField("shipping_address", address_out),
                    StructField("bank_match_status", StringType()),
                    StructField("reconciliation_status", StringType()),
                    StructField("custom_fields", custom_fields),
                    StructField("attachments", ArrayType(attachment)),
                    StructField("payment", payment),
                    StructField("next_approvers", ArrayType(approver)),
                    StructField("rejected_by", rejected_by),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                    StructField("created_at", TimestampType()),
                    StructField("updated_at", TimestampType()),
                ]
            ),
            "bills": StructType(
                [
                    StructField("internal_id", LongType()),
                    StructField("number", LongType()),
                    StructField("company_id", LongType()),
                    StructField("company_name", StringType()),
                    StructField("company_currency", StringType()),
                    StructField("vendor_id", LongType()),
                    StructField("vendor_name", StringType()),
                    StructField("currency_iso_4217_code", StringType()),
                    StructField("exchange_rate", StringType()),
                    StructField("memo", StringType()),
                    StructField("amount", StringType()),
                    StructField("amount_due", StringType()),
                    StructField("paid_total", StringType()),
                    StructField("date", DateType()),
                    StructField("transaction_date", DateType()),
                    StructField("due_date", DateType()),
                    StructField("supply_date", DateType()),
                    StructField("place_of_supply", StringType()),
                    StructField("record_status", StringType()),
                    StructField("approval_status", StringType()),
                    StructField("recurring_record_number", LongType()),
                    StructField("purchase_order_number", LongType()),
                    StructField("reference_number", StringType()),
                    StructField("term_id", LongType()),
                    StructField("term_name", StringType()),
                    StructField("transaction_ids", ArrayType(LongType())),
                    StructField("tax", bill_tax),
                    StructField("tax_registration_numbers", tax_registration_numbers),
                    StructField("bank_match_status", StringType()),
                    StructField("reconciliation_status", StringType()),
                    StructField("custom_fields", custom_fields),
                    StructField("attachments", ArrayType(attachment)),
                    StructField("next_approvers", ArrayType(approver)),
                    StructField("rejected_by", rejected_by),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                    StructField("created_at", TimestampType()),
                    StructField("updated_at", TimestampType()),
                ]
            ),
            "customers": StructType(
                [
                    StructField("id", LongType()),
                    StructField("name", StringType()),
                    StructField("unique_id", StringType()),
                    StructField("email", StringType()),
                    StructField("website", StringType()),
                    StructField("customer_type", StringType()),
                    StructField("is_active", BooleanType()),
                    StructField("phone", StringType()),
                    StructField("full_address", address_in),
                    StructField("shipping_address", address_in),
                    StructField("approval_status", StringType()),
                    StructField("custom_fields", custom_fields),
                    StructField("next_approvers", ArrayType(approver)),
                    StructField("rejected_by", rejected_by),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                ]
            ),
            "vendors": StructType(
                [
                    StructField("id", LongType()),
                    StructField("name", StringType()),
                    StructField("vendor_type", StringType()),
                    StructField("company_id", LongType()),
                    StructField("company_name", StringType()),
                    StructField("customer_account_number", StringType()),
                    StructField("single_address", StringType()),
                    StructField("country", StringType()),
                    StructField("unique_id", StringType()),
                    StructField("website", StringType()),
                    StructField("email", StringType()),
                    StructField("is_active", BooleanType()),
                    StructField("phone", StringType()),
                    StructField("is_1099_eligible", BooleanType()),
                    StructField("tin", StringType()),
                    StructField("tin_type", StringType()),
                    StructField("record_status", StringType()),
                    StructField("address", vendor_address),
                    StructField("approval_status", StringType()),
                    StructField("custom_fields", custom_fields),
                    StructField("next_approvers", ArrayType(approver)),
                    StructField("rejected_by", rejected_by),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                ]
            ),
            "items": StructType(
                [
                    StructField("id", LongType()),
                    StructField("name", StringType()),
                    StructField("sku", StringType()),
                    StructField("description", StringType()),
                    StructField("item_type", StringType()),
                    StructField("is_active", BooleanType()),
                    StructField("record_status", StringType()),
                    StructField("product_tax_code_id", LongType()),
                    StructField("expense_account_id", LongType()),
                    StructField("income_account_id", LongType()),
                    StructField("deferral_account_id", LongType()),
                    StructField("asset_account_id", LongType()),
                    StructField("discount_account_id", LongType()),
                    StructField("default_classification_line_ids", ArrayType(LongType())),
                    StructField("default_rev_rec_method", StringType()),
                    StructField("default_rev_rec_invoice_frequency", StringType()),
                    StructField("default_rev_rec_invoice_interval", LongType()),
                    StructField("created_by", audit_actor),
                    StructField("updated_by", audit_actor),
                ]
            ),
        }


    TABLE_SCHEMAS = _build_schemas()


    class DualEntryLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the DualEntry public REST API."""

        # ------------------------------------------------------------------
        # Construction & helpers
        # ------------------------------------------------------------------

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)

            api_key = options.get("api_key")
            if not api_key:
                raise ValueError(
                    "DualEntry connector requires 'api_key' option (a DualEntry "
                    "public API key sent in the X-API-KEY header)."
                )

            base_url = options.get("base_url") or DEFAULT_BASE_URL
            self._root = base_url.rstrip("/") + "/"

            # The OpenAPI security scheme is an apiKey header literally named
            # ``X-API-KEY`` carrying the raw key — no ``Bearer`` prefix.
            self._headers = {
                "X-API-KEY": api_key,
                "Accept": "application/json",
            }

            # Cap cursors at init time so Trigger.AvailableNow always terminates.
            # Parse the formatted string back so ``_init_dt`` carries the same
            # millisecond precision as stored cursors (which come from
            # ``_format_ts``); otherwise sub-ms microseconds would make the
            # caught-up fast-path in ``_read_incremental`` never compare equal.
            self._init_ts_iso = _format_ts(datetime.now(timezone.utc))
            self._init_dt = _parse_ts(self._init_ts_iso)

        def _url(self, path: str) -> str:
            """Join *path* (no leading slash) onto the API root."""
            return urljoin(self._root, path.lstrip("/"))

        def _request(self, path: str, params: dict | None = None) -> requests.Response:
            """GET *path* with retry on 429/5xx; honour ``Retry-After``.

            DualEntry 429s carry a ``Retry-After`` header (seconds); waiting the
            advertised time (not just our own backoff) matters because the 429
            counts against the token bucket. Every request carries an explicit
            timeout so the connector cannot hang on a stuck socket; transport-level
            ``RequestException`` errors propagate so the framework retries the
            microbatch.
            """
            backoff = INITIAL_BACKOFF
            resp: requests.Response | None = None
            for attempt in range(MAX_RETRIES):
                resp = requests.get(
                    self._url(path),
                    headers=self._headers,
                    params=params or {},
                    timeout=DEFAULT_TIMEOUT,
                )
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    return resp

                sleep_s = backoff
                retry_after = _retry_after_seconds(resp)
                if retry_after is not None:
                    sleep_s = max(sleep_s, retry_after)
                logger.warning(
                    "DualEntry %s returned %s; retrying in %.1fs (attempt %d/%d)",
                    path,
                    resp.status_code,
                    sleep_s,
                    attempt + 1,
                    MAX_RETRIES,
                )
                if attempt < MAX_RETRIES - 1:
                    _sleep(sleep_s)
                    backoff *= 2

            assert resp is not None  # for type-checkers; always set inside the loop
            return resp

        def _get_json(self, path: str, params: dict | None = None):
            """Issue a GET, raise on non-2xx, return the decoded JSON body."""
            resp = self._request(path, params=params)
            if resp.status_code // 100 != 2:
                raise RuntimeError(
                    f"DualEntry API GET {path} failed with HTTP {resp.status_code}: "
                    f"{resp.text[:500]}"
                )
            return resp.json()

        @staticmethod
        def _unwrap_records(body) -> list:
            """Return the records list from a DualEntry response body.

            List responses wrap the record array in a top-level ``items`` key
            alongside a ``count`` field. Tolerate a bare array in case the envelope
            ever changes; return ``[]`` for anything else so callers can iterate
            without guarding.
            """
            if isinstance(body, list):
                return body
            if isinstance(body, dict):
                inner = body.get("items")
                if isinstance(inner, list):
                    return inner
            return []

        # ------------------------------------------------------------------
        # LakeflowConnect API
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            # DualEntry has no discovery endpoint; tables are statically known.
            return list(TABLE_SCHEMAS.keys())

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            # Return a fresh copy so callers cannot mutate the module-level dict.
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)
            if TABLE_METADATA[table_name]["ingestion_type"] == "snapshot":
                return self._read_snapshot(table_name, start_offset, table_options)
            return self._read_incremental(table_name, start_offset, table_options)

        # ------------------------------------------------------------------
        # Snapshot reads (accounts / customers / vendors / items)
        # ------------------------------------------------------------------

        def _read_snapshot(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Full-refresh read for snapshot tables.

            Returns ``{"done": True}`` after the first call so subsequent calls
            within the same Trigger.AvailableNow trigger short-circuit (per the
            ``end_offset == start_offset`` termination contract). Records are yielded
            raw, exactly as the API returns them.
            """
            if start_offset and start_offset.get("done"):
                return iter([]), start_offset

            path = TABLE_ENDPOINTS[table_name]
            limit = _page_size(table_options)

            def generate() -> Iterator[dict]:
                row_offset = 0
                while True:
                    params = {
                        "limit": str(limit),
                        "offset": str(row_offset),
                        "ordering": "id",
                    }
                    records = self._unwrap_records(self._get_json(path, params=params))
                    yield from records
                    if len(records) < limit:
                        return
                    row_offset += limit

            return generate(), {"done": True}

        # ------------------------------------------------------------------
        # Incremental reads (journal_entries / invoices / bills)
        # ------------------------------------------------------------------

        def _read_incremental(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Bounded ``updated_at``-range read with offset continuation.

            Offset shapes:
              ``{"cursor": <iso>}``                        — caught-up steady state.
              ``{"since": ..., "until": ..., "offset": N}`` — mid-range, produced
                  only when ``max_records_per_batch`` split a range across
                  microbatches. ``since``/``until`` stay pinned so the row offset
                  stays stable for the rest of the range.

            A new range spans ``[cursor - lookback_seconds, _init_ts]``; when a page
            returns fewer than ``limit`` records the range is drained and the cursor
            advances to the range's upper bound. The very first sync has no lower
            bound (full backfill) unless ``start_timestamp`` is supplied. Records
            are yielded raw, exactly as the API returns them.
            """
            offset = dict(start_offset or {})
            limit = _page_size(table_options)
            max_records = int(table_options.get("max_records_per_batch", str(sys.maxsize)))

            if offset.get("until"):
                # Resume a partially-drained range with its bounds pinned.
                since = offset.get("since")
                until = offset["until"]
                row_offset = int(offset.get("offset", 0))
            else:
                cursor = offset.get("cursor")
                if cursor and _parse_ts(cursor) >= self._init_dt:
                    # Caught up to init time — short-circuit so the trigger
                    # terminates (end_offset == start_offset contract).
                    return iter([]), start_offset
                until = self._init_ts_iso
                row_offset = 0
                if cursor:
                    lookback = max(
                        0,
                        int(table_options.get("lookback_seconds", str(DEFAULT_LOOKBACK_SECONDS))),
                    )
                    since = _format_ts(_parse_ts(cursor) - timedelta(seconds=lookback))
                else:
                    since = table_options.get("start_timestamp")

            path = TABLE_ENDPOINTS[table_name]
            params: dict[str, str] = {
                "updated_before": until,
                "limit": str(limit),
                "ordering": "updated_at",
            }
            if since:
                params["updated_after"] = since

            if max_records >= sys.maxsize:
                # Unbounded (the default): stream pages lazily so driver memory
                # tracks a single page, not the whole range. A short page drains
                # the range; the cursor then advances to its upper bound. Because
                # the range always fully drains here, the end offset is known up
                # front (like the snapshot path), so no accumulation is needed.
                def generate() -> Iterator[dict]:
                    off = row_offset
                    while True:
                        page_records = self._unwrap_records(
                            self._get_json(path, params={**params, "offset": str(off)})
                        )
                        yield from page_records
                        if len(page_records) < limit:
                            return
                        off += limit

                return generate(), {"cursor": until}

            # Bounded by ``max_records_per_batch``: accumulate up to the cap (memory
            # stays bounded by the cap) so the split offset can be computed before
            # the tuple is returned.
            records: list[dict] = []
            off = row_offset
            while True:
                page_records = self._unwrap_records(
                    self._get_json(path, params={**params, "offset": str(off)})
                )
                records.extend(page_records)
                if len(page_records) < limit:
                    # Range drained — advance the cursor to its upper bound.
                    return iter(records), {"cursor": until}
                off += limit
                if len(records) >= max_records:
                    # Split the range across microbatches; the cap applies at page
                    # granularity so resuming at ``off`` never skips the tail of a
                    # partially-emitted page.
                    next_offset: dict = {"until": until, "offset": off}
                    if since:
                        next_offset["since"] = since
                    return iter(records), next_offset

        # ------------------------------------------------------------------
        # Validation
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {sorted(TABLE_SCHEMAS)}"
                )


    # ------------------------------------------------------------------
    # Module-level helpers
    # ------------------------------------------------------------------


    def _sleep(seconds: float) -> None:
        """Indirection over ``time.sleep`` so retries are trivial to stub in tests."""
        import time

        time.sleep(seconds)


    def _retry_after_seconds(resp: requests.Response) -> float | None:
        """Return the ``Retry-After`` wait (seconds) advertised on a response.

        DualEntry 429s carry a numeric ``Retry-After`` header; 5xx responses may
        carry one too. Returns ``None`` when the header is absent or unparseable so
        the caller falls back to exponential backoff.
        """
        raw = resp.headers.get("Retry-After")
        if not raw:
            return None
        try:
            return float(raw)
        except ValueError:
            return None


    def _page_size(table_options: dict[str, str]) -> int:
        """Resolve the ``limit`` page-size option, clamped to the server max."""
        return max(1, min(int(table_options.get("limit", str(DEFAULT_PAGE_SIZE))), MAX_PAGE_SIZE))


    def _format_ts(dt: datetime) -> str:
        """Format a datetime as the ISO-8601 UTC shape DualEntry uses (ms + Z)."""
        return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


    def _parse_ts(value: str) -> datetime:
        """Parse an ISO-8601 timestamp string (Z or offset) into an aware datetime."""
        if not value:
            raise ValueError("empty timestamp string")
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = DualEntryLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
