# ==============================================================================
# Merged Lakeflow Source: hubspot_extended
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

import base64
import json
import time
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Iterator, Sequence

import requests
from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)

    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]

    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }

    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)

    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")

    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)

    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))

    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)

    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")

    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")

    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")

    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")

    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }

    def parse_value(
        value: Any, field_type: DataType
    ) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(
                f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}"
            )

    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )

    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """

    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """

    ########################################################
    # src/databricks/labs/community_connector/sources/hubspot_extended/hubspot_extended_schemas.py
    ########################################################

    def _properties(*names: str) -> StructType:
        return StructType([StructField(name, StringType(), True) for name in names])

    def _crm_schema(properties: StructType) -> StructType:
        return StructType(
            [
                StructField("id", StringType(), True),
                StructField("createdAt", TimestampType(), True),
                StructField("updatedAt", TimestampType(), True),
                StructField("archived", BooleanType(), True),
                StructField("properties", properties, True),
            ]
        )

    ASSOCIATION_RESULT_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("type", StringType(), True),
        ]
    )

    ASSOCIATION_COLLECTION_SCHEMA = StructType(
        [StructField("results", ArrayType(ASSOCIATION_RESULT_SCHEMA), True)]
    )

    CRM_ASSOCIATIONS_SCHEMA = StructType(
        [
            StructField("contacts", ASSOCIATION_COLLECTION_SCHEMA, True),
            StructField("companies", ASSOCIATION_COLLECTION_SCHEMA, True),
            StructField("deals", ASSOCIATION_COLLECTION_SCHEMA, True),
            StructField("tickets", ASSOCIATION_COLLECTION_SCHEMA, True),
            StructField("line_items", ASSOCIATION_COLLECTION_SCHEMA, True),
            StructField("products", ASSOCIATION_COLLECTION_SCHEMA, True),
            StructField("quotes", ASSOCIATION_COLLECTION_SCHEMA, True),
        ]
    )

    def _crm_schema_with_associations(properties: StructType) -> StructType:
        return StructType(
            _crm_schema(properties).fields
            + [StructField("associations", CRM_ASSOCIATIONS_SCHEMA, True)]
        )

    CONTACTS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "lastmodifieddate",
        "firstname",
        "lastname",
        "email",
        "phone",
        "company",
        "jobtitle",
        "lifecyclestage",
        "hubspot_owner_id",
    )

    COMPANIES_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "name",
        "domain",
        "website",
        "industry",
        "city",
        "state",
        "country",
        "numberofemployees",
        "annualrevenue",
        "hubspot_owner_id",
    )

    DEALS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "dealname",
        "dealstage",
        "pipeline",
        "dealtype",
        "amount",
        "closedate",
        "hs_is_closed",
        "hs_is_closed_won",
        "hubspot_owner_id",
    )

    TICKETS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "subject",
        "content",
        "hs_pipeline",
        "hs_pipeline_stage",
        "hs_ticket_priority",
        "hs_ticket_category",
        "source_type",
        "closed_date",
        "hubspot_owner_id",
    )

    LINE_ITEMS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "name",
        "description",
        "hs_sku",
        "hs_product_id",
        "price",
        "amount",
        "quantity",
        "discount",
        "hs_line_item_currency_code",
    )

    PRODUCTS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "name",
        "description",
        "hs_sku",
        "price",
        "hs_cost_of_goods_sold",
        "hs_product_type",
        "hs_url",
        "recurringbillingfrequency",
        "tax",
    )

    LEADS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_lead_name",
        "hs_lead_label",
        "hs_lead_type",
        "hs_lead_stage",
        "hs_pipeline",
        "hs_pipeline_stage",
        "hs_lead_disqualification_reason",
        "hubspot_owner_id",
    )

    QUOTES_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_title",
        "hs_status",
        "hs_expiration_date",
        "hs_quote_amount",
        "hs_currency",
        "hs_language",
        "hs_terms",
        "hs_public_url_key",
        "hs_pdf_download_link",
        "hubspot_owner_id",
    )

    FEEDBACK_SUBMISSIONS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_submission_name",
        "hs_survey_type",
        "hs_survey_id",
        "hs_value",
        "hs_response_group",
        "hs_sentiment",
        "hs_content",
        "hs_contact_id",
    )

    APPOINTMENTS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_appointment_name",
        "hs_appointment_start",
        "hs_appointment_end",
        "hs_appointment_location",
        "hs_appointment_status",
        "hs_pipeline",
        "hs_pipeline_stage",
        "hubspot_owner_id",
    )

    LISTINGS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_listing_name",
        "hs_listing_type",
        "hs_listing_status",
        "hs_listing_url",
        "hs_price",
        "hs_currency",
        "hs_address",
        "hubspot_owner_id",
    )

    ORDERS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_order_name",
        "hs_order_status",
        "hs_order_amount",
        "hs_currency_code",
        "hs_source_store",
        "hs_fulfillment_status",
        "hs_payment_status",
        "hs_external_order_id",
    )

    CARTS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_cart_name",
        "hs_cart_status",
        "hs_cart_amount",
        "hs_currency_code",
        "hs_source_store",
        "hs_abandoned_cart_url",
        "hs_external_cart_id",
    )

    COMMERCE_PAYMENTS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_payment_name",
        "hs_payment_status",
        "hs_payment_amount",
        "hs_currency_code",
        "hs_payment_method",
        "hs_processor",
        "hs_external_payment_id",
    )

    SUBSCRIPTIONS_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_subscription_name",
        "hs_subscription_status",
        "hs_recurring_billing_period",
        "hs_next_billing_date",
        "hs_start_date",
        "hs_end_date",
        "hs_currency_code",
        "hs_subscription_amount",
    )

    INVOICES_PROPERTIES = _properties(
        "hs_object_id",
        "createdate",
        "hs_lastmodifieddate",
        "hs_invoice_number",
        "hs_invoice_status",
        "hs_invoice_amount",
        "hs_balance_due",
        "hs_due_date",
        "hs_currency_code",
        "hs_external_invoice_id",
    )

    _ENGAGEMENT_BASE = (
        "hs_object_id",
        "hs_createdate",
        "hs_lastmodifieddate",
        "hs_timestamp",
        "hubspot_owner_id",
    )

    CALLS_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_call_title",
        "hs_call_body",
        "hs_call_direction",
        "hs_call_disposition",
        "hs_call_duration",
        "hs_call_from_number",
        "hs_call_to_number",
        "hs_call_status",
    )

    EMAILS_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_email_subject",
        "hs_email_text",
        "hs_email_direction",
        "hs_email_status",
        "hs_email_from_email",
        "hs_email_to_email",
        "hs_email_message_id",
        "hs_email_thread_id",
        "hs_email_headers",
    )

    MEETINGS_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_meeting_title",
        "hs_meeting_body",
        "hs_meeting_location",
        "hs_meeting_start_time",
        "hs_meeting_end_time",
        "hs_meeting_outcome",
    )

    TASKS_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_task_subject",
        "hs_task_body",
        "hs_task_status",
        "hs_task_priority",
        "hs_task_type",
        "hs_task_is_completed",
        "hs_task_completion_date",
    )

    NOTES_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_note_body",
        "hs_attachment_ids",
    )

    COMMUNICATIONS_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_communication_body",
        "hs_communication_channel_type",
        "hs_communication_logged_from",
        "hs_communication_global_id",
        "hs_body_preview",
    )

    POSTAL_MAIL_PROPERTIES = _properties(
        *_ENGAGEMENT_BASE,
        "hs_postal_mail_body",
        "hs_attachment_ids",
    )

    OWNER_TEAM_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("name", StringType(), True),
            StructField("primary", BooleanType(), True),
        ]
    )

    OWNERS_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("email", StringType(), True),
            StructField("type", StringType(), True),
            StructField("firstName", StringType(), True),
            StructField("lastName", StringType(), True),
            StructField("userId", LongType(), True),
            StructField("userIdIncludingInactive", LongType(), True),
            StructField("createdAt", TimestampType(), True),
            StructField("updatedAt", TimestampType(), True),
            StructField("archived", BooleanType(), True),
            StructField("teams", ArrayType(OWNER_TEAM_SCHEMA), True),
        ]
    )

    PIPELINE_STAGE_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("label", StringType(), True),
            StructField("displayOrder", LongType(), True),
            StructField("metadata", StringType(), True),
            StructField("archived", BooleanType(), True),
            StructField("createdAt", TimestampType(), True),
            StructField("updatedAt", TimestampType(), True),
        ]
    )

    PIPELINES_SCHEMA = StructType(
        [
            StructField("id", StringType(), True),
            StructField("label", StringType(), True),
            StructField("displayOrder", LongType(), True),
            StructField("archived", BooleanType(), True),
            StructField("createdAt", TimestampType(), True),
            StructField("updatedAt", TimestampType(), True),
            StructField("stages", ArrayType(PIPELINE_STAGE_SCHEMA), True),
        ]
    )

    TABLE_SCHEMAS: dict[str, StructType] = {
        "contacts": _crm_schema(CONTACTS_PROPERTIES),
        "companies": _crm_schema(COMPANIES_PROPERTIES),
        "deals": _crm_schema(DEALS_PROPERTIES),
        "tickets": _crm_schema(TICKETS_PROPERTIES),
        "calls": _crm_schema(CALLS_PROPERTIES),
        "emails": _crm_schema(EMAILS_PROPERTIES),
        "meetings": _crm_schema(MEETINGS_PROPERTIES),
        "tasks": _crm_schema(TASKS_PROPERTIES),
        "notes": _crm_schema(NOTES_PROPERTIES),
        "owners": OWNERS_SCHEMA,
        "pipelines": PIPELINES_SCHEMA,
        "line_items": _crm_schema(LINE_ITEMS_PROPERTIES),
        "products": _crm_schema(PRODUCTS_PROPERTIES),
        "leads": _crm_schema_with_associations(LEADS_PROPERTIES),
        "quotes": _crm_schema_with_associations(QUOTES_PROPERTIES),
        "feedback_submissions": _crm_schema_with_associations(FEEDBACK_SUBMISSIONS_PROPERTIES),
        "appointments": _crm_schema_with_associations(APPOINTMENTS_PROPERTIES),
        "listings": _crm_schema_with_associations(LISTINGS_PROPERTIES),
        "orders": _crm_schema_with_associations(ORDERS_PROPERTIES),
        "carts": _crm_schema_with_associations(CARTS_PROPERTIES),
        "commerce_payments": _crm_schema_with_associations(COMMERCE_PAYMENTS_PROPERTIES),
        "subscriptions": _crm_schema_with_associations(SUBSCRIPTIONS_PROPERTIES),
        "invoices": _crm_schema_with_associations(INVOICES_PROPERTIES),
        "communications": _crm_schema_with_associations(COMMUNICATIONS_PROPERTIES),
        "postal_mail": _crm_schema_with_associations(POSTAL_MAIL_PROPERTIES),
    }

    _CDC_METADATA = {
        "primary_keys": ["id"],
        "cursor_field": "updatedAt",
        "ingestion_type": "cdc",
    }

    TABLE_METADATA: dict[str, dict] = {
        "contacts": dict(_CDC_METADATA),
        "companies": dict(_CDC_METADATA),
        "deals": dict(_CDC_METADATA),
        "tickets": dict(_CDC_METADATA),
        "calls": dict(_CDC_METADATA),
        "emails": dict(_CDC_METADATA),
        "meetings": dict(_CDC_METADATA),
        "tasks": dict(_CDC_METADATA),
        "notes": dict(_CDC_METADATA),
        "line_items": dict(_CDC_METADATA),
        "products": dict(_CDC_METADATA),
        "leads": dict(_CDC_METADATA),
        "quotes": dict(_CDC_METADATA),
        "feedback_submissions": dict(_CDC_METADATA),
        "appointments": dict(_CDC_METADATA),
        "listings": dict(_CDC_METADATA),
        "orders": dict(_CDC_METADATA),
        "carts": dict(_CDC_METADATA),
        "commerce_payments": dict(_CDC_METADATA),
        "subscriptions": dict(_CDC_METADATA),
        "invoices": dict(_CDC_METADATA),
        "communications": dict(_CDC_METADATA),
        "postal_mail": dict(_CDC_METADATA),
        "owners": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
        "pipelines": {"primary_keys": ["id"], "ingestion_type": "snapshot"},
    }

    SUPPORTED_TABLES: list[str] = list(TABLE_SCHEMAS)

    CRM_OBJECTS: set[str] = {
        "contacts",
        "companies",
        "deals",
        "tickets",
        "calls",
        "emails",
        "meetings",
        "tasks",
        "notes",
        "line_items",
        "products",
        "leads",
        "quotes",
        "feedback_submissions",
        "appointments",
        "listings",
        "orders",
        "carts",
        "commerce_payments",
        "subscriptions",
        "invoices",
        "communications",
        "postal_mail",
    }

    SEARCH_CURSOR_PROPERTIES: dict[str, str] = {
        "contacts": "lastmodifieddate",
        "companies": "hs_lastmodifieddate",
        "deals": "hs_lastmodifieddate",
        "tickets": "hs_lastmodifieddate",
        "calls": "hs_lastmodifieddate",
        "emails": "hs_lastmodifieddate",
        "meetings": "hs_lastmodifieddate",
        "tasks": "hs_lastmodifieddate",
        "notes": "hs_lastmodifieddate",
        "line_items": "hs_lastmodifieddate",
        "products": "hs_lastmodifieddate",
        "leads": "hs_lastmodifieddate",
        "quotes": "hs_lastmodifieddate",
        "feedback_submissions": "hs_lastmodifieddate",
        "appointments": "hs_lastmodifieddate",
        "listings": "hs_lastmodifieddate",
        "orders": "hs_lastmodifieddate",
        "carts": "hs_lastmodifieddate",
        "commerce_payments": "hs_lastmodifieddate",
        "subscriptions": "hs_lastmodifieddate",
        "invoices": "hs_lastmodifieddate",
        "communications": "hs_lastmodifieddate",
        "postal_mail": "hs_lastmodifieddate",
    }

    def crm_request_properties(table_name: str) -> list[str]:
        properties = TABLE_SCHEMAS[table_name]["properties"].dataType
        assert isinstance(properties, StructType)
        return [field.name for field in properties.fields]

    ########################################################
    # src/databricks/labs/community_connector/sources/hubspot_extended/hubspot_extended.py
    ########################################################

    class HubspotExtendedLakeflowConnect(LakeflowConnect):
        def __init__(self, options: dict) -> None:
            self.access_token = options["access_token"]
            self.base_url = "https://api.hubapi.com"
            self.headers = {
                "Authorization": f"Bearer {self.access_token}",
                "Content-Type": "application/json",
            }
            self._init_ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"

        def list_tables(self) -> list[str]:
            return SUPPORTED_TABLES

        def get_table_schema(self, table_name: str, table_options: dict[str, str]) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(self, table_name: str, table_options: dict[str, str]) -> dict:
            self._validate_table(table_name)
            return TABLE_METADATA[table_name]

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            self._validate_table(table_name)

            if table_name in CRM_OBJECTS:
                return self._read_crm_object(table_name, start_offset)
            if table_name == "owners":
                return self._read_snapshot("/crm/v3/owners")
            if table_name == "pipelines":
                return self._read_snapshot("/crm/v3/pipelines/deals")

            raise ValueError(f"Unsupported table: {table_name}")

        def _read_crm_object(
            self, table_name: str, start_offset: dict
        ) -> tuple[Iterator[dict], dict]:
            checkpoint = start_offset.get("updatedAt") if start_offset else None
            if checkpoint and checkpoint >= self._init_ts:
                return iter(()), start_offset

            if checkpoint:
                records = self._fetch_search_records(table_name, checkpoint)
            else:
                records = self._fetch_list_records(f"/crm/v3/objects/{table_name}")

            latest_updated = checkpoint
            for record in records:
                updated_at = record.get("updatedAt")
                if updated_at and (latest_updated is None or updated_at > latest_updated):
                    latest_updated = updated_at

            if latest_updated and latest_updated > self._init_ts:
                latest_updated = self._init_ts
            offset = {"updatedAt": latest_updated} if latest_updated else {}
            return iter(records), offset

        def _read_snapshot(self, path: str) -> tuple[Iterator[dict], dict]:
            return iter(self._fetch_list_records(path)), {}

        def _fetch_list_records(self, path: str) -> list[dict]:
            records: list[dict] = []
            after = None
            while True:
                params = {"limit": "100"}
                if after:
                    params["after"] = after
                response = requests.get(
                    f"{self.base_url}{path}",
                    headers=self.headers,
                    params=params,
                    timeout=60,
                )
                self._raise_for_status(response)
                payload = response.json()
                records.extend(payload.get("results", []))
                after = payload.get("paging", {}).get("next", {}).get("after")
                if not after:
                    return records
                time.sleep(0.1)

        def _fetch_search_records(self, table_name: str, checkpoint: str) -> list[dict]:
            records: list[dict] = []
            after = None
            modified_property = SEARCH_CURSOR_PROPERTIES[table_name]
            value = str(self._iso_to_epoch_millis(checkpoint))
            while True:
                body = {
                    "filterGroups": [
                        {
                            "filters": [
                                {
                                    "propertyName": modified_property,
                                    "operator": "GTE",
                                    "value": value,
                                }
                            ]
                        }
                    ],
                    "sorts": [{"propertyName": modified_property, "direction": "ASCENDING"}],
                    "limit": 100,
                    "properties": crm_request_properties(table_name),
                }
                if after:
                    body["after"] = after
                response = requests.post(
                    f"{self.base_url}/crm/v3/objects/{table_name}/search",
                    headers=self.headers,
                    json=body,
                    timeout=60,
                )
                self._raise_for_status(response)
                payload = response.json()
                records.extend(payload.get("results", []))
                after = payload.get("paging", {}).get("next", {}).get("after")
                if not after:
                    return records
                time.sleep(0.1)

        @staticmethod
        def _iso_to_epoch_millis(value: str) -> int:
            try:
                return int(datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp() * 1000)
            except ValueError:
                return 0

        @staticmethod
        def _raise_for_status(response: requests.Response) -> None:
            if response.status_code >= 400:
                raise RuntimeError(f"HubSpot API error: {response.status_code} {response.text}")

        @staticmethod
        def _validate_table(table_name: str) -> None:
            if table_name not in TABLE_SCHEMAS:
                raise ValueError(
                    f"Unsupported table: {table_name}. Supported tables are: {SUPPORTED_TABLES}"
                )

    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = HubspotExtendedLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"

    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; " f"got: {decoded!r}"
            )
        return decoded

    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded

    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {k: v for k, v in self.options.items() if k != IS_DELETE_FLOW}

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass

    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(self.table_name, self.table_options, start)

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass

    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = (
                _decode_list_of_str_option(TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)) or []
            )
            table_configs = _decode_dict_option(TABLE_CONFIGS, self.options.get(TABLE_CONFIGS))
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(NAMESPACE, self.options[NAMESPACE])
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [{"namespace": namespace, TABLE_NAME: tn} for tn in sorted(tables)]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]

    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(
                options
            )  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(
                        self.options, schema, self.lakeflow_connect
                    )
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)

    spark.dataSource.register(LakeflowSource)
